apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    spec:
      volumes:
       - name: postgres-pvc
         persistentVolumeClaim:
           claimName: database-pvc 
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: postgres-pvc
              subPath: postgres
          env:
           - name: PGPASSWORD
             valueFrom:
               secretKeyRef:
                name: pgpassword
                key: PGPASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
